Recipient.create([
{recipient_name: "3D Forged", city: "", state: "", country: "US", category_id: "13", description: "3D printing, computers, technology"},
{recipient_name: "Almasry Alyoum", city: "", state: "", country: "EG", category_id: "7", description: "Arabic, daily newspaper"},
{recipient_name: "American Society of Business Publication Editors", city: "Wheaton", state: "IL", country: "US", category_id: "3", description: "Association for full-time and freelance editors and writers in business, trade, and specialty press"},
{recipient_name: "B2I Technologies, Inc.", city: "", state: "", country: "US", category_id: "3", description: "Financial data, research, analytics"},
{recipient_name: "Bartender Journey", city: "", state: "", country: "US", category_id: "1", description: "BLOG-Spirits, Cocktails, Beer & Wine"},
{recipient_name: "Black Voices", city: "", state: "", country: "US", category_id: "1", description: "African-American, multicultural"},
{recipient_name: "Bourbon & Oak", city: "", state: "", country: "US", category_id: "1", description: "BLOG-Spirits, Cocktails, Beer & Wine"},
{recipient_name: "BusinessFM", city: "", state: "", country: "FR", category_id: "11", description: "Radio station "},
{recipient_name: "Canada Stock Channel", city: "Jericho", state: "NY", country: "US", category_id: "13", description: "Financial"},
{recipient_name: "Capital One Investing", city: "Seattle", state: "WA", country: "US", category_id: "3", description: "Online brokerage firm"},
{recipient_name: "Cindy Parrett", city: "", state: "HI", country: "US", category_id: "1", description: "Retail & Consumer, Parenting, Family, Children Blog"},
{recipient_name: "Cocktail Crafty", city: "", state: "", country: "US", category_id: "1", description: "Retail & Consumer, beverage, alcohol"},
{recipient_name: "Cori’s Cozy Corner", city: "Ft Lauderdale", state: "FL", country: "US", category_id: "1", description: "Retail & Consumer, parenting"},
{recipient_name: "dailyLead: Aerospace Industries Association", city: "Washington", state: "DC", country: "US", category_id: "13", description: "aerospace, defense, aviation, homeland security, information technology news"},
{recipient_name: "dailyLead: Food Marketing Institute", city: "Washington", state: "DC", country: "US", category_id: "13", description: "food, beverages, retail, supermarkets news"},
{recipient_name: "dailyLead: USTelecom [United States Telecom Association]", city: "Washington", state: "DC", country: "US", category_id: "13", description: "technology, telecommunications, internet, multimedia, online news updates"},
{recipient_name: "Dealernews - The Voice of Powersports Retailers", city: "Santa Monica", state: "CA", country: "US", category_id: "13", description: "Transportation, Automotive news"},
{recipient_name: "DiabetesPro", city: "Horsham", state: "PA", country: "US", category_id: "13", description: "biotechnology, pharmaceuticals, medical, healthcare online resource center"},
{recipient_name: "DIY Design Mom", city: "New York", state: "NY", country: "US", category_id: "1", description: "Retail & Consumer, parenting, children blog"},
{recipient_name: "Dow Jones Newsletter (Gale Cengage Learning)", city: "", state: "", country: "US", category_id: "9", description: "Localized content from DJ"},
{recipient_name: "EDACafe (IBSystems)", city: "Campbell", state: "CA", country: "US", category_id: "13", description: "delivers the latest EDA industry commentary, news, product reviews, articles, events and resources"},
{recipient_name: "Encore Magazine", city: "Quebec", state: "QC", country: "CA", category_id: "5", description: "entertainment magazine"},
{recipient_name: "eTV-Media, Inc.", city: "Glen Harbor", state: "NY", country: "US", category_id: "3", description: ""},
{recipient_name: "FashionNetAsia.com (UBM Asia)", city: "Hong Kong", state: "", country: "CN", category_id: "3", description: "fashion/textiles"},
{recipient_name: "Finalaya", city: "", state: "", country: "IN", category_id: "3", description: "Financials"},
{recipient_name: "Games Press", city: "", state: "", country: "", category_id: "13", description: "computers, electronics, electronic gaming, gamers"},
{recipient_name: "Grape Experiences", city: "", state: "", country: "US", category_id: "13", description: "Retail & Consumer, Food, Beverages, Alcohol"},
{recipient_name: "Greenlichen", city: "", state: "", country: "IN", category_id: "13", description: ""},
{recipient_name: "Harlem World", city: "New York", state: "NY", country: "US", category_id: "5", description: "guide to all thinhs happening in Harlem, NY"},
{recipient_name: "HRmarketer.com (Fisher Vista LLC)", city: "Capitola", state: "CA", country: "US", category_id: "13", description: "human resources, marketing, advertising, employee benefits, insurance, labor"},
{recipient_name: "Insite (Gale Cengage Learning)", city: "", state: "", country: "US", category_id: "13", description: "financial"},
{recipient_name: "InSite 2 Database (Gale Cengage Learning)", city: "", state: "", country: "US", category_id: "13", description: "financial"},
{recipient_name: "Insite 2 Pro (Gale Cengage Learning)", city: "", state: "", country: "US", category_id: "13", description: "financial"},
{recipient_name: "InSite Database (Gale Cengage Learning)", city: "", state: "", country: "US", category_id: "13", description: "financial"},
{recipient_name: "International Foundation of Employee Benefit Plans", city: "Brookfield", state: "WI", country: "US", category_id: "3", description: "healthcare, financial, human resources, staffing, benefits, insurance"},
{recipient_name: "Intoxicologist", city: "", state: "", country: "US", category_id: "1", description: "blog about cocktails"},
{recipient_name: "Investor Concepts", city: "Burbank", state: "CA", country: "US", category_id: "13", description: "financial news and data"},
{recipient_name: "Inyo Register", city: "Bishop", state: "CA", country: "US", category_id: "7", description: "local newspaper"},
{recipient_name: "IP &Science - Thomson Reuters (formerly Thomson Scientific) (formerly Current Drugs)", city: "Philadelphia", state: "PA", country: "US", category_id: "3", description: "pharmaceutical, healthcare, biotechnology"},
{recipient_name: "Jiji Press", city: "", state: "", country: "JP", category_id: "3", description: "Media company"},
{recipient_name: "June Grace", city: "", state: "", country: "US", category_id: "1", description: "Retail & Consumer, parenting, children, family"},
{recipient_name: "Kansas Tourism", city: "Topeka", state: "KS", country: "US", category_id: "13", description: "Travel and tourism in the state of Kansas"},
{recipient_name: "Kentucky Hotel & Lodging Association", city: "Louisville", state: "KY", country: "US", category_id: "13", description: "travel and leisure in the state of Kentucky"},
{recipient_name: "Kids InfoBits (Gale Cengage Learning)", city: "", state: "", country: "US", category_id: "13", description: "Kids educational website"},
{recipient_name: "YellowBrix", city: "Alexandria", state: "VA", country: "US", category_id: "13", description: "information and syndication"},
{recipient_name: "Telvent DTN (fka Data Transmission Network) (fka DTN Financial Services)", city: "Omaha", state: "NE", country: "US", category_id: "3", description: "media, financial"},
{recipient_name: "StockHouse.com (Stockgroup Information Systems Inc.) (fka Stockgroup.com Media, Inc.; fka Stock Research Group)", city: "Vancouver", state: "BC", country: "CA", category_id: "13", description: "financial"},
{recipient_name: "SOA World Magazine (SYS-CON Media)", city: "Montvale", state: "NJ", country: "US", category_id: "5", description: "technology, computers, multimedia, hardware, software, internet technology magazine"},
{recipient_name: "Smartnet.com.tw (SysPower Corp.)", city: "", state: "", country: "TW", category_id: "13", description: "financial advice and planning website"},
{recipient_name: "Shihua International Financial Information", city: "", state: "", country: "CN", category_id: "13", description: "financial advice and planning website"},
{recipient_name: "Science 2.0 (Scientific Blogging)", city: "Folsom", state: "CA", country: "US", category_id: "13", description: "Physical Sciences, Earth Sciences, Biology, Neurosciences, biotechnology, healthcare educational website"},
{recipient_name: "Vance Publishing ", city: "Lincolnshire", state: "IL", country: "US", category_id: "10", description: "Media publisher"},
{recipient_name: "PR News Online (Access Intelligence)", city: "Rockville", state: "MD", country: "US", category_id: "3", description: "hones and grows PR and marketing professionals’ skills in social media, crisis management, digital PR, measurement, employee relations, media training, "},
{recipient_name: "Student Resource Center (Gale Cengage Learning)", city: "", state: "", country: "US", category_id: "3", description: "sells educational resources for children "},
{recipient_name: "SCNow.com", city: "Florence", state: "SC", country: "US", category_id: "13", description: "website dedicated to reporting nationwide and local news to the state of South Carolina"},
{recipient_name: "Pavementonline.com", city: "Ft Atkinson", state: "WI", country: "US", category_id: "13", description: "website for construction professionals"},
{recipient_name: "Packaging Strategies (BNP Media)", city: "Deerfield", state: "IL", country: "US", category_id: "13", description: "website for those in the plastics and packaging industry"},
{recipient_name: "Onmedica.net", city: "", state: "", country: "GB", category_id: "13", description: "online medical information"},
{recipient_name: "Telegraph India", city: "", state: "", country: "IN", category_id: "13", description: "Local and national news from India"},
{recipient_name: "Nickle's Daily Oil Bulletin (Business Information Group) (JuneWarren-Nickle's Network)", city: "Calgary", state: "AB", country: "CA", category_id: "13", description: "Daily news for those in the oil, gas and energy industry"},
{recipient_name: "Newsworthy ", city: "Fairfax", state: "VA", country: "US", category_id: "13", description: "information and media website"},
{recipient_name: "NewsTex", city: "New York", state: "NY", country: "US", category_id: "13", description: "information and media website"},
{recipient_name: "Newscan.com ", city: "", state: "", country: "CA", category_id: "13", description: "organizes and distributes news information"},
{recipient_name: "Sentieo", city: "Indian Harbor", state: "FL", country: "US", category_id: "3", description: "finance "},
{recipient_name: "Pörssihuone.fi ", city: "", state: "", country: "FI", category_id: "13", description: "banking and finance website"},
{recipient_name: "Newsday's 'In the Garage'", city: "Glen Cove", state: "NY", country: "US", category_id: "13", description: "Automobile and transit website"},
{recipient_name: "min online (Access Intelligence)", city: "Rockville", state: "MD", country: "US", category_id: "10", description: "advertising, magazine, publishing, media"},
{recipient_name: "Metro Networks (Westwood One)", city: "New York", state: "NY", country: "US", category_id: "3", description: ""},
{recipient_name: "Mental Help Net (CenterSite, LLC)", city: "Columbus", state: "OH", country: "US", category_id: "13", description: "website to help those suffering from mental illness "},
{recipient_name: "Meal & Drink", city: "", state: "", country: "", category_id: "13", description: "Curated news about food companies"},
{recipient_name: "Skipah’s Realm - Divorced father speaking his mind", city: "", state: "", country: "US", category_id: "1", description: "personal blog for divorced dads"},
{recipient_name: "The Math Lovin' Momma", city: "", state: "IA", country: "US", category_id: "1", description: "lifestyle blog"},
{recipient_name: "Marketing and Advertising Reference Service (Gale Cengage Learning)", city: "Dayton", state: "OH", country: "US", category_id: "3", description: ""},
{recipient_name: "Momma of 4 Cutiez", city: "Kalamazoo", state: "MI", country: "US", category_id: "1", description: "lifestyle and travel blog"},
{recipient_name: "Mark’s Marketing Blog", city: "", state: "", country: "US", category_id: "1", description: "business services blog"},
{recipient_name: "Momma Without A Clue", city: "", state: "NC", country: "US", category_id: "1", description: "lifestyle blog"},
{recipient_name: "Tidbits of Experience", city: "Orangeburb", state: "SC", country: "US", category_id: "1", description: "lifestyle blog"},
{recipient_name: "Oenologist: The People of Wine (CityRoom)", city: "Port Townsend ", state: "WA", country: "US", category_id: "1", description: "retail & consumer, food, beverages, alcoholic beverages, spirits, travel & leisure blog"},
{recipient_name: "SKNR.net", city: "", state: "", country: "US", category_id: "13", description: "Computers, Electronics, electronic gaming website"},
{recipient_name: "Nevada Hotel and Lodging Association", city: "Henderson", state: "NV", country: "US", category_id: "3", description: "travel and lesiure in Nevada"},
{recipient_name: "Mammoth Times [Mammoth Lakes, CA] (Surf New Media)", city: "Mammoth", state: "CA", country: "US", category_id: "7", description: "local newspaper"},
{recipient_name: "Minster Community Post [Minster, OH] (Surf New Media)", city: "Minster", state: "OH", country: "US", category_id: "7", description: "local newspaper"},
{recipient_name: "The Antlers American [Antlers, OK] (Surf New Media)", city: "Antlers", state: "OK", country: "US", category_id: "7", description: "local newspaper"},
{recipient_name: "The Post and Mail [Columbia City, IN] (Surf New Media)", city: "Columbia City", state: "IN", country: "US", category_id: "7", description: "local newspaper"},
{recipient_name: "OTT Travel", city: "", state: "NY", country: "US", category_id: "3", description: "full service agency specializing in corporate and government travel"},
{recipient_name: "Wine Chronicles", city: "", state: "", country: "US", category_id: "1", description: "Retail & Consumer, Food, Beverages, Alcohol blog"},
{recipient_name: "WINEormous", city: "Temecula", state: "CA", country: "US", category_id: "13", description: "Retail & Consumer, Food, Beverages, Alcohol website"},
{recipient_name: "WardsAuto", city: "", state: "", country: "US", category_id: "13", description: "covers the latest news, data and analysis for today's auto industry "},
{recipient_name: "SiliconValleyGlobe.com", city: "", state: "CA", country: "US", category_id: "13", description: "technology news and updates"},
{recipient_name: "True Colors", city: "", state: "CT", country: "US", category_id: "3", description: "non-profit organization that works with other social service agencies, schools, organizations, and within communities to ensure that the needs of sexual and gender minority youth are both recognized and competently met. "},
{recipient_name: "The Arcade Corner", city: "", state: "", country: "US", category_id: "13", description: "gaming website"},
{recipient_name: "The Pilot News [Plymouth, IN] (Surf New Media)", city: "Plymouth", state: "IN", country: "US", category_id: "7", description: "local newspaper"},
{recipient_name: "Tequila & Oak", city: "", state: "", country: "US", category_id: "13", description: "alcohol and beverage website"},
{recipient_name: "Rum & Oak", city: "", state: "", country: "US", category_id: "13", description: "alcohol and beverage website"},
{recipient_name: "Witch On Wine", city: "", state: "", country: "", category_id: "1", description: "alcohol and beverage website"},
{recipient_name: "Vindulge", city: "", state: "", country: "US", category_id: "1", description: "alcohol and beverage website"},
{recipient_name: "The Gourmez", city: "", state: "", country: "US", category_id: "1", description: "alcohol and beverage website"},
{recipient_name: "World Food Travel Association", city: "", state: "", country: "", category_id: "3", description: "a non-profit and non-governmental organization (NGO) and the world’s leading authority on food tourism. "}
])