Industry.update(
  [
    15,16,17,18,119,120,121,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,46,47,48,49,51,52,53,54,55,56,58,59,60,61,62,63,64,65,66,67,68,69,71,72,73,74,75,77,76,78,79,1,2,3,4,5,6,8,7,9,10,11,12,13,14,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,45,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,50,115,116,117,118
    ],
  [
    {description: "News from banks, savings and loans, thrifts, pawn shops, mortgage lenders, brokers, investment houses, pension funds, stock and bond traders, credit unions, nondeposit trust facilities, credit agencies."},
    {description: "Health and medical insurers, insurance agents and carriers, insurance brokers and services, insurance rating agencies."},
    {description: "Property/Casualty, life, medical insurers, insurance agents and carriers, insurance brokers and services, insurance rating agencies."},
    {description: "News from mutual fund firms, banks, investment houses and asset management organizations about mutual funds."},
    {description: "Producers, processors, wholesalers of beverages, both alcoholic and non-alcoholic.  Makers of soft drinks, beer, wine and other liquors."},
    {description: "Makers and distributors of alcoholic beverages, bottlers and drink carrier manufacturers as well as drink mixers.  "},
    {description: "Producers, processors, wholesalers of non-alcoholic beverages and makers of soft drinks. "},
    {description: "Makers of computers, software storage devices, semiconductors, computer peripheral equipment, computer programming services, computer processing and data preparation, integrated systems design, digital scanners, maintenance and repair, calculating and accounting machines, copiers, electronic capacitors, resistors, coils, transformers, batteries."},
    {description: "Makers of personal identity management products for a wide variety of applications and transactions through fingerprint identification, proprietary subcutaneous palm identification, image processing, facial recognition, 3D facial imaging and recognition technology."},
    {description: "Technology companies, products and innovations in the Broadcast industry: remote broadcasting, satellite broadcasting, broadcast towers, antennas, mobile broadcasting or data broadcasting."},
    {description: "Developers of interactive games for all platforms, including mobile, web-based, PC-based and consoles. Makers of electronic games and gaming systems."},
    {description: "Makers of computer systems, desktop workstations, notebook and laptop computers, network servers."},
    {description: "Makers and providers of networking technology, local and wide area networks (LANs and WANs), frame relay, ATM."},
    {description: "Makers and developers of computer software, device drivers, operating systems, system utilities, file managers, freeware and shareware."},
    {description: "Makers of home audio and video equipment, televisions, still and motion electronic cameras, home automation and security systems, telephones and accessories, electronic games and toys, audio and video recording devices, home, mobile, and portable audio systems, cellular telephones and personal communications devices, music electronics, home health care electronic devices."},
    {description: "Producers of e-commerce software applications and technology, news about e-commerce/e-tailing."},
    {description: "Makers, developers and distributors of integrated circuits, semiconductors (also code SEM), electronic capacitors, resistors, coils, transformers, transistors, diodes, connectors, crystals, relays, resistors, switches."},
    {description: "The Electronic Design Automation industry supplies products, services and tools used by electronic engineers who develop highly complex computer chips, and the larger electronic systems in which they reside."},
    {description: "Makers and providers of electronic test and measurement equipment, benchmark utilities, design and test validation solutions, automatic test equipment (ATE), fault tolerance software."},
    {description: "Makers and developers of computer and network security products and services, Internet firewalls, intrusion detection, encryption software, virus protection, virtual private networks (VPNs)."},
    {description: "Makers of video games, CD-ROMs, interactive media or anything to do with content on the internet including web pages, search engines, online providers and e-commerce.  "},
    {description: "The science and technology of building electronic circuits and devices (like robots) from single atoms and molecules."},
    {description: "Makers of CD ROMs, modems and faxes, printers, scanners, monitors, and disks."},
    {description: "Providers of Radio Frequency Identification technologies, applications & technology."},
    {description: "Makers and developers of semiconductors.  (A semiconductor is a chip or integrated circuit.  Semiconductors are used in computers, DVD players, cell phones, household appliances, video games, along with many other products.)"},
    {description: "Blogging, social media optimization and social network marketing while developing the careers of well-known bloggers, podcasters, community builders and social networkers."},
    {description: "Web developers of on-line interactive media, consumer applications and portals, or anything to do with the internet including web pages, search engines, online providers and e-commerce."},
    {description: "News of national interest from universities, any public or private school, trade schools, education-related foundations or organizations, school districts, government or independent agencies dealing with education, libraries, makers of educational materials or items relating to schools and educational-related awards, scholarships and fellowships."},
    {description: "News from or about colleges, universities, professional or trade schools and other institutions of higher learning."},
    {description: "Publishers of Books/cirriculums for home schooling. Also include programs that foster or support home schooling programs."},
    {description: "Producers and distributors of music products, movies, amusement and recreation services, theatrical producers, bands, orchestras, actors and other entertainment groups, television, radio and cable networks, stations, producers, programmers and owners, concert promoters and ticket sellers, talent agencies, videos and video games."},
    {description: "For news about painting, drawing and sketching, sculpture, animation, graphic design and other visual arts, artists and artist groups, museums, galleries, arts organizations."},
    {description: "News about the film and motion picture industry, producers and distributors of movies, film actors, directors and technicians, cinematography, animation, special effects, film festivals and societies, movie theaters. "},
    {description: "News about the music industry, producers and distributors of music products, musicians and singers, music videos."},
    {description: "Radio networks, stations, producers, programmers and owners, professional and amateur radio associations."},
    {description: "Television networks, stations, producers, programmers and owners, professional TV associations and organizations."},
    {description: "News about environmental products and services, including waste management, waste treatment, recycling, remediation, mining/oil industry site reclamation, disposal and cleanup of nuclear and radioactive materials, conservation, land, mineral, forest and wildlife protection and preservation, air and water resource management."},
    {description: "Companies involved in not only recycling, water purification, sewage treatment, remediation, flue gas treatment, solid waste management and renewable energy but also alternative fuels, new means of generating energy and energy efficiency and the invention, design and application of chemical products and processes to reduce or to eliminate the use and generation of hazardous substances.  The field of “green technology” encompasses a continuously evolving group of methods and materials, from techniques for generating energy to non-toxic cleaning products."},
    {description: "Producers, processors, wholesalers of food, fish hatcheries and preserves, seasonings and flavorings, meat packers, producers of dairy products, dog, cat and other pet food."},
    {description: "Producers, processors, wholesalers of organic food."},
    {description: "News from or about hospitals, nursing homes, rehabilitation treatment centers, HMOs, clinics, diseases, health care insurance, health care organizations, news of doctors, dentists, chiropractors, optometrists, home care services, local, state and federal health agencies. "},
    {description: "For news about biotechnology, biomedical companies, biopharmaceuticals, bioinformatics, genomics, gene therapy, biopesticides and biotreatment products."},
    {description: "News pertaining to dentists, dental schools, cosmetic dentistry treatments. National and local dental organizations; pharmaceutical companies that develop products for the prevention and detection of tooth decay; companies that design and manufacture sophisticated laser systems used in dental and aesthetic medical practices."},
    {description: "Directives from the CDC or pharmaceutical companies developing drugs and/or vaccines for infectious diseases. "},
    {description: "Makers of medical equipment including diagnostic devices, laboratory analytical instruments, surgical appliances and supplies, optical instruments and lenses, dental equipment and supplies, x-ray apparatus, and ophthalmic goods"},
    {description: "Releases about medical science, research, clinical studies, procedures, makers of medical equipment, diagnostic devices, laboratory analytical instruments, surgical appliances and supplies, optical instruments and lenses, dental equipment and supplies, x-ray apparatus, ophthalmic goods, all prescription and over-the-counter pharmaceuticals."},
    {description: "News from mental health facilities/hospitals/organizations or about mental health conditions, treatments, or education"},
    {description: "Releases about pharmaceutical research, clinical studies, all prescription and over-the-counter pharmaceuticals."},
    {description: "News about alternative medicine and practices, nutrition, fitness, ergonomics."},
    {description: "Producers (not retailers) of household furniture and fixtures, appliances, jewelry, toys, photographic equipment, beauty aids, make-up, sporting goods."},
    {description: "Producers (not retailers) of personal care products: fragrances, toiletries, oral care personal hygene, beauty aids and make-up. "},
    {description: "News about the fashion industry, designers, collections, shows, make-up, accessories, style, modelling."},
    {description: "Manufacturers and retailers of household furniture, rugs and fixtures also include office furniture designers and manufacturers."},
    {description: "Producers and retailers of DIY, household fixtures and appliances as well as publications that illustrate or explain home renovation techniques."},
    {description: "Producers and retailers of household products including vacuum cleaners and cleaning supplies."},
    {description: "Retailers, designers and makers of jewelry. "},
    {description: "Makers and distributors of office products, supplies, furniture, stationery."},
    {description: "Makers of clothing and apparel, including shoes, textile mills, finishers of textiles, carpets and rugs, hats, leather products, sheets and towels, textile industry groups and unions."},
    {description: "Companies and products in the Toy industry."},
    {description: "Miners of coal, metals and gems, metal workers, steel mills, organizations that represent metal workers or employees of the mining industry."},
    {description: "Suppliers of tooling and industrial materials, mineral exploration and development"},
    {description: "Makers of industrial and commercial machinery, including steam, gas and hydraulic turbines, internal combustion engines, conveyors, cranes, hoists, tractors, stackers, machine tools and accessories, pumps, bearings, compressors."},
    {description: "News from not only precious metals mining companies but also producers of coal, iron ore concentrate."},
    {description: "Gold, silver, platinum, diamonds, rubies, emeralds, etc."},
{description: ""},
    {description: "Use for all information about advertising and public relations firms, for other types of companies’ releases about their advertising accounts, campaigns and advertising personnel, advertising policy, volume or rates. "},
    {description: "Makers of aerospace products and components, weapons, military equipment, defense contractors, suppliers and components for missiles, satellites, rockets, space systems."},
    {description: "Use for agricultural firms, livestock, dairy farmers, food growers (but not processors [FOD] or retailers [REA]), makers of farm equipment and machinery, supplies, fertilizer, agriculture-related pesticides, seeds, farm management, farm bureaus, farm-product raw materials, farm product warehousing and storage, farm worker unions (also give LBR subject code) and organizations."},
    {description: "Makers of chemicals, plastics, chemical and fertilizer mineral mining, chemical preparations, inorganic pigments, resins, adhesives and sealants, paints, pesticides, synthetic rubber, cleaning, polishing and sanitation preparations, distributors of chemicals."},
    {description: "Builders and contractors of residences, industrial and office buildings and warehouses, highways, bridges and tunnels, makers of construction machinery and equipment, construction materials and techniques, sand and gravel, concrete, carpentry, plumbing and heating supply, masonry, flooring, plastering, insulation, drywall."},
    {description: "Manufacturers, providers, retailers and installers of heating, ventilation and air-conditioning equipment and its components for residential, industrial and office use."},
    {description: "Companies doing business with the Department of Homeland Security or special interest groups dealing with homeland Security issues. "},
    {description: "Content coming from attorneys or law firms."},
    {description: "News from companies listed on the Nasdaq SmallCap Stock Market (but not on the National Market) and all companies listed on the Over-the-Counter (OTC) Bulletin Board or pink sheets, or other OTC Bulletin Board or SmallCap-related stories."},
    {description: "News about or from companies who are contracting or subcontracting certain job functions to an outside company"},
    {description: "Timber tracts, forest nurseries, forestry services, lumber and wood pulp, paper and paperboard mills, makers of corrugated and solid fiber boxes, paperboard, cardboard, paper products (such as tissues, disposable diapers) wood containers, coated and laminated paper, converted paper and paperboard products."},
    {description: "Tobacco growers, processors and makers of tobacco products, makers of smoking-cessation products."},
    {description: "Companies that advise on the selection, development and retention of a company’s workforces.  Outsourcing companies, corporate recruiters, management consulting firms and  companies offering online job search services."},
    {description: "Producers of books, magazines, newspapers, texts, directories, databases, news services, information suppliers and resellers, information retrieval services, news syndicates. "},
    {description: "News from or about book publishers (also code PUB), booksellers (also code REA), bookbinding & conservation, book-related accessories, book reviews, book signings."},
    {description: "News from publishers of periodicals or journals, or about magazine articles "},
    {description: "Realtors, realty investment firms, mortgage firms (if the release is about a specific realty transaction), government or other agencies that specialize in housing."},
    {description: "Commercial realtors, realty investment firms, real estate and business investment funds investing in commercial real estate projects."},
    {description: "Overseas realtors, realty investment firms, mortgage firms (if the release is about a specific realty transaction), government or other agencies that specialize in housing."},
    {description: "Residential realtors,  government or other agencies that specialize in housing."},
    {description: "Sellers (not producers) of consumer products including department stores, bookstores, toy stores, home and garden supply stores, food and grocery stores, apparel and accessory stores, drug stores, furniture stores, etc., direct mail order sellers, news about malls, retail developments and e-commerce/e-tailing."},
    {description: "All industries designed to assist a bride in planning her wedding.  Including, but not limited to, Wedding Planners, wedding event publishers, both online and print; bridal destination sites; wedding website publishers; wedding dresses; catering halls and venues."},
    {description: "Restaurants (including fast food chains), restaurant suppliers, unions and organizations serving restaurant employees, restaurant franchising corporations."},
    {description: "News about grocery supermarkets and supermarket chains."},
    {description: "Athletic competitions, sports facilities, sports equipment manufacturers and retailers, sports travel, ski and golf resorts, motor sports and recreational sports activities."},
    {description: "Venues and Including television outlets that broadcast sporting events and broadcasting services vital to the delivery of live sports and entertainment events."},
    {description: "For news from sports equipment manufacturers and sporting goods accessories. "},
    {description: "Makers of telecommunications equipment and suppliers of telecommunications services, including telephones, cellular, fiber optics, pagers and Cable TV products (not programming)."},
    {description: "News about the technology behind Web site planning, development and management, companies involved in the technology that drives the websites, the nuts-and-bolts of the Internet."},
    {description: "Producers and content providers of steaming video and multimedia products.  Ipods, cell phones, PDAs, etc."},
    {description: "(The coming Web 3.0) or Web Development"},
    {description: "Suppliers of telecommunications services, including telephones, cellular, fiber optics and Cable TV  (not programming)."},
    {description: "Makers of telecommunications equipment including telephones, cellular, fiber optics, PDAs and Cable TV products (not programming)."},
    {description: "Makers of telecommunications equipment and suppliers of VoIP telecommunications and broadband services. "},
    {description: "Makers of telecommunications equipment and suppliers of wireless services, including cell phones, PDAs, and wireless networking as well as GPS units."},
    {description: "Trucking and freight moving companies, parcel delivery services, freight railroads, moving lines, mass transit systems (LEI for passenger railroads like Amtrak and long distance buses like Greyhound) and rental truck operations."},
    {description: "Air freight service providers, air cargo shipping, freight forwarders and international shipping worldwide."},
    {description: "Makers of cars, trucks, buses, motorcycles, RVs, jeeps, parts, equipment, supplies and accessories, car and truck rental, leasing and financing firms, gasoline producers and retailers, tires, automotive dealers, repair shops and other services, auto racking, auto unions, auto emissions."},
    {description: "Shipbuilders, makers of maritime products, water transportation of freight, marine cargo handling, towing, tugboat and barge services, marinas."},
    {description: "Railroads, trucking and freight moving companies, freight railroads, moving lines, mass transit systems and rental truck operations. "},
    {description: "Trucking and freight moving companies, parcel delivery services, moving lines, and rental truck operations."},
    {description: "News about travel, travel agents, travel promotions, air fares and routes, passenger railroads, long-distance buses, cruise lines, hotels, resorts, travel clubs, organizations and services, visitors bureaus, national and international tourism and convention groups."},
    {description: "Use for all news from airlines, including passenger, charter and cargo carriers, airplane orders and deliveries, makers of airplanes, airplane engines, parts and accessories, airports, flying fields, airport terminal services, air courier services, news of air routes, landing fees, landing rights, air traffic, air traffic control."},
    {description: "For news about tourist attractions including sporting and recreational camps, amusement and theme parks, golf courses, museums, national parks, and visitors’ bureaus."},
    {description: "Owners, builders, operators of casinos, makers of casino and gaming equipment and accessories, bookmakers, makers and suppliers of lottery equipment, state lottery promotions and results, tribal gaming commissions, gaming legislation and casino/gaming regulators."},
    {description: "News about hotels and resorts, including long-term residential-stay establishments. "},
    {description: "For news about travel, travel agents, travel promotions, air fares and routes, passenger railroads, long-distance buses, ski areas, cruise lines, hotels, resorts, sporting and recreational camps, amusement and theme parks, golf courses, travel clubs, organizations and services, visitors’ bureaus, national and international tourism and convention groups."},
    {description: "For all news pertaining to passenger airlines, including airplane orders and deliveries, airports, flying fields, airport terminal services, news of air routes, landing fees, air traffic, air traffic control. "},
    {description: "Regulated public utilities supplying electric, natural gas, water and sewage systems, hydroelectric, solar and nuclear energy, makers of equipment for utilities, builders and operators of power plants and other utility facilities, news from public utilities regulators."},
    {description: "Companies providing green or environmental technologies; alternative or sustainable energies, such as wind, solar and hydro power; also include alternative energy research."},
    {description: "Regulated public utilities supplying electric, hydroelectric, solar and nuclear energy, makers of equipment for utilities, builders and operators of power plants and other utility facilities, news from public utilities regulators. "},
    {description: "Regulated public utilities supplying natural gas, makers of equipment for utilities, builders and operators of utility facilities. "},
    {description: "Companies involved in the exploration for, extraction, refining, supply and marketing of oil, petroleum and natural gas, drilling equipment, wells, rigs, exploration and field services, co-generation and waste-to-energy facilities, makers of oil and gas field machinery and equipment, builders and operators of pipelines and gas transmission systems".}
    {description: "Regulated water utilities, including the makers of equipment, builders and operators."}
  ]
)
