Subject.update(
  [1,2,3,5,4,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70],
  [{description: "News from accounting firms, or releases about accounting regulations, procedures and standards."},
    {description: "Acquisitions, mergers or takeovers, such as when one company purchases another company, a unit of another company, or merges with another company. "},
    {description: "Releases from or about Advocacy Groups (political and social advocacy, lobbying and special-interest organizations), including non-government organizations (NGOs), that are non-factual expressions of opinions, beliefs or views; comments on current events; proposing or denouncing legislation; proposing or denouncing a person or group’s actions; making a demand of a person or group; issuing a call for action to or against a person or group; or launching a campaign or initiative for or against an issue."},
    {description: "All things pertaining to pets, products for pets, and other animal-related items, including competitive shows (e.g.: dog shows, horse races), television programs, animal hospitals, circuses and Humane Societies/Associations."},
    {description: "For news about Animal Welfare (including but not limited to) organizations dedicated to animal rights, both domestic and wild."},
    {description: "For news about or targeted to Asians and Asian Americans. Not only Asian Americans of East Asian and Southeast Asian descent (Chinese, Korean, Japanese, Vietnamese, Thai, Filipino, etc.) but also people with ancestry in South Asia, or what’s referred to as the Indian Subcontinent (Indian, Pakistani, Sri Lankan, Bangladeshi). "},
    {description: "To be used only on copy related to class actions and investigation releases."},
    {description: "For releases about the presentation or receipt of awards and other honors."},
    {description: "Bankruptcy news, companies filing Chapter 7 or 11, emerging from bankruptcy, making bankruptcy-related restructuring plans or pacts with creditors."},
    {description: "For news about or targeted to African Americans"},
    {description: "For use with releases from credit ratings agencies (e.g., Duff & Phelps, Fitch, Moody’s, Standard & Poor’s, A.M. Best)."},
    {description: "For releases about children and teenagers and issues pertaining to them, such as education, child safety, parenting and child care, children’s health, juvenile crime, teen sexuality, child support, youth rights. "},
    {description: "News about pending, in process or completed clinical trials.  Medical discoveries, breakthroughs or advancements. "},
    {description: "Conference call announcements.  This would also include a company’s webcast presentation at a conference."},
    {description: "Congressional, senatorial, gubernatorial and presidential campaign news.  The outcome of a poll, declaration of candidacy or endorsement."},
    {description: "For news about conservation/recycling."},
    {description: "For use when a company announces receipt or awarding of a contract with another company."},
    {description: "For news about corporate expansion or a company’s plans for corporate expansion. "},
    {description: "For news about philanthropic investment, diversity, community development, corporate governance, environment, business ethics, human rights, and workplace issues."},
    {description: "Public company cash and stock dividend announcements and limited partnership quarterly cash distributions."},
    {description: "For releases involving domestic policy issues, including but not limited to: education, health, welfare, justice, transportation, environment, labor, and veterans’ affairs."},
    {description: "Quarterly or annual earnings releases from publicly traded companies"},
    {description: "Projections or forecasts from publicly traded companies about their upcoming earnings, such as “Due to Sluggish Economy, XYZ Expects to Report a Loss for First Quarter.”"},
    {description: "News, statistics, trends, analyses and forecasts relating to the national or state economy."},
    {description: "For news about Environmental issues."},
    {description: "For news about Environmental Policy issues."},
    {description: "For news from or about European government bodies."},
    {description: "For use when companies receive FDA approvals "},
    {description: "Federal and state legislation, such as pending legislation, the outcome of a congressional vote on a new law, statements from companies or organizations responding to a piece of legislation."},
    {description: "Policy news from Federal executive branch or federal agencies, such as EPA announcements or FDA, HUD or IRS releases or reaction to the policies made by those government agencies."},
    {description: "For releases about financing agreements."},
    {description: "For stories about matters of international relations or the interests of the home country in foreign countries.  Also, for stories related to a country’s policy toward other countries or reaction to a country’s foreign policy."},
    {description: "Future Events indicate any content that provides a date for any occurrence happening tomorrow or later."},
    {description: "Handicapped/Disabled-oriented news  "},
    {description: "Hispanic-oriented news."},
    {description: "For releases from firms issuing buy/sell recommendations or offering other advice or analysis on stocks."},
    {description: "Joint venture announcements between two or more companies. To be considered a joint venture, two companies must invest to form a third legal entity, from which they both profit. A joint announcement will not necessarily be about a joint venture."},
    {description: "For releases issued by or about unions or organizations representing workers."},
    {description: "For releases about legal issues and opinions, discussion of new laws and legal procedures and announcements by law firms and legal groups."},
    {description: "Lesbian/Gay/Bisexual-oriented news."},
    {description: "For releases about companies signing or announcing licensing and/or marketing agreements."},
    {description: "For media advisories and press invitations that are meant for the media only."},
    {description: "Native American-oriented news. "},
    {description: "New product or service announcements, such as a release about a new piece of software that has been developed, or the introduction of new airfare/hotel packages. "},
    {description: "News from nonprofit organizations and charities, or releases about nonprofit and charity services and fundraising."},
    {description: "Obituary Announcements. For releases announcing the death of a person."},
    {description: "For use specifically with stock, bond, debenture or warrant offerings, including SEC registration statements, announcements of an offering becoming effective, notice of a planned offering or announcements of the results of a stock offering. "},
    {description: "Oil/gas discoveries, such as “Oil Co. USA Reports Oil Discoveries in Gulf of Mexico.”"},
    {description: "For use on news releases issued by companies listed on the Nasdaq Small-Cap Stock Market (but not on the National Market) and all companies listed on the Over-the-Counter (OTC) Bulletin Board or pink sheets."},
    {description: "All things related to patents -- also covers new patents."},
    {description: "Personnel announcements, elections or appointments of new personnel, promotions, resignations, retirements, firings.  Also for large, company-wide personnel announcements."},
    {description: "Product Recalls."},
    {description: "For releases about public safety."},
    {description: "For news about real estate transactions, such as the purchase of a number of existing warehouses or monthly home sales."},
    {description: "News releases about religion or religious issues."},
    {description: "Corporate restructuring or recapitalization announcements."},
    {description: "For monthly auto and retail sales reports only."},
    {description: "Senior Citizen-related news."},
    {description: "For public companies announcing the establishment of a shareholders’ rights plan. "},
    {description: "Small Business Services.  Products and services specifically targeted for small businesses. "},
    {description: "Socially responsible investing, also known as sustainable investing or ethical investing, describes an investment strategy which seeks to maximize both financial return and social good.  In general, socially responsible investors favor corporate best practices that promote environmental stewardship, consumer protection, human rights, and diversity. "},
    {description: "For releases about stock splits."},
    {description: "For releases about survey and poll results and research studies. "},
    {description: "Use for tender offers, which are offers to buy outstanding shares of a company -- the same as a proposed acquisition."},
    {description: "For all things pertaining to international trade policies, practices, and treaties. "},
    {description: "For news that is originating from a trade show or conference."},
    {description: "U.S. State Policy News"},
    {description: "For use when a company is seeking, giving or getting venture capital or risk capital (financing provided by wealthy independent investors, banks, and financing companies to help new businesses get started and grow). "},
    {description: "Veterans’ affairs, health issues, benefits or philanthropic endeavors. "},
    {description: "Women-oriented news."}]
    )
