# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ product_name: 'Chicago' }, { product_name: 'Copenhagen' }])
#   Mayor.create(product_name: 'Emanuel', city: cities.first)
# MediaPointProduct.create(media_point_id: '1', product_id: '1')
# MediaPointProduct.create(media_point_id: '1', product_id: '2')
# MediaPointProduct.create(media_point_id: '1', product_id: '2')

Product.create([
  {code: 'ALA',
  product_name: 'Alabama Newsline',
  base_price: '350',
  length_price: '115'},
  {code: 'ALK',
  product_name: 'Alaska Newsline',
  base_price: '350',
  length_price: '115'},
  {code: 'ARI',
  product_name: 'Arizona Newsline',
  base_price: '350',
  length_price: '115'},
  {code: 'ARK',
  product_name: 'Arkansas Newsline',
  base_price: '350',
  length_price: '115'},
  {code: 'ATL',
  product_name: 'Atlanta Newsline',
  base_price: '350',
  length_price: '115'},
  {code: 'BOS',
  product_name: 'Boston Newsline',
  base_price: '350',
  length_price: '115'},
  {code: 'CAL',
  product_name: 'California Newsline',
  base_price: '350',
  length_price: '115'},
  {code: 'CAP',
  product_name: 'Dc Public Interest Newsline',
  base_price: '235',
  length_price: '65'},
  {code: 'CAR',
  product_name: 'Carolinas Newsline',
  base_price: '445',
  length_price: '115'},
  {code: 'CFL',
  product_name: 'Central Florida Newsline',
  base_price: '350',
  length_price: '115'},
  {code: 'CGO',
  product_name: 'Chicago Newsline',
  base_price: '350',
  length_price: '115'},
  {code: 'CGR',
  product_name: 'Chicago Area Newsline',
  base_price: '350',
  length_price: '115'},
  {code: 'CIN',
  product_name: 'Cincinnati Newsline',
  base_price: '350',
  length_price: '115'},
  {code: 'CLV',
  product_name: 'Cleveland Newsline',
  base_price: '350',
  length_price: '115'},
  {code: 'COL',
  product_name: 'Colorado Newsline',
  base_price: '350',
  length_price: '115'},
  {code: 'CON',
  product_name: 'Connecticut Newsline',
  base_price: '350',
  length_price: '115'},
  {code: 'COU',
  product_name: 'Columbus Newsline',
  base_price: '350',
  length_price: '115'},
  {code: 'CPA',
  product_name: 'Central Pennsylvania Newsline',
  base_price: '350',
  length_price: '115'},
  {code: 'CRN',
  product_name: 'Washington D.c. Regional Newsline',
  base_price: '445',
  length_price: '115'},
  {code: 'DAL',
  product_name: 'Dallas/ft. Worth Newsline',
  base_price: '350',
  length_price: '115'},
  {code: 'DEL',
  product_name: 'Delaware Newsline',
  base_price: '350',
  length_price: '115'},
  {code: 'DEN',
  product_name: 'Denver Newsline',
  base_price: '350',
  length_price: '115'},
  {code: 'DET',
  product_name: 'Detroit Newsline',
  base_price: '350',
  length_price: '115'},
  {code: 'DOC',
  product_name: 'Washington Dc Newsline',
  base_price: '350',
  length_price: '115'},
  {code: 'EAS',
  product_name: 'Eastern Package (northeast & Southeast',
  base_price: '575',
  length_price: '150'},
  {code: 'ECP',
  product_name: 'Dc Public Interest Plus Newsline',
  base_price: '255',
  length_price: '65'},
  {code: 'EN1',
  product_name: 'Us1 Entertainment Newsline',
  base_price: '795',
  length_price: '205'},
  {code: 'FLA',
  product_name: 'Florida Newsline',
  base_price: '350',
  length_price: '115'},
  {code: 'GEO',
  product_name: 'Georgia Newsline',
  base_price: '350',
  length_price: '115'},
  {code: 'GOT',
  product_name: 'Greater Ohio Newsline',
  base_price: '445',
  length_price: '115'},
  {code: 'HAW',
  product_name: 'Hawaii Newsline Newsline',
  base_price: '350',
  length_price: '115'},
  {code: 'HOU',
  product_name: 'Houston Newsline',
  base_price: '350',
  length_price: '115'},
  {code: 'IDA',
  product_name: 'Idaho Newsline',
  base_price: '350',
  length_price: '115'},
  {code: 'ILL',
  product_name: 'Illinois Newsline',
  base_price: '350',
  length_price: '115'},
  {code: 'IND',
  product_name: 'Indianapolis Newsline',
  base_price: '350',
  length_price: '115'},
  {code: 'INI',
  product_name: 'Indiana Newsline',
  base_price: '350',
  length_price: '115'},
  {code: 'IWA',
  product_name: 'Iowa Newsline',
  base_price: '350',
  length_price: '115'},
  {code: 'KAN',
  product_name: 'Kansas Newsline',
  base_price: '350',
  length_price: '115'},
  {code: 'KEN',
  product_name: 'Kentucky Newsline',
  base_price: '350',
  length_price: '115'},
  {code: 'KSC',
  product_name: 'Kansas City Newsline',
  base_price: '350',
  length_price: '115'},
  {code: 'LAS',
  product_name: 'Las Vegas Newsline',
  base_price: '350',
  length_price: '115'},
  {code: 'LOU',
  product_name: 'Louisiana Newsline',
  base_price: '350',
  length_price: '115'},
  {code: 'LSA',
  product_name: 'Los Angeles Newsline',
  base_price: '350',
  length_price: '115'},
  {code: 'MAI',
  product_name: 'Maine Newsline',
  base_price: '350',
  length_price: '115'},
  {code: 'MAR',
  product_name: 'Maryland Newsline',
  base_price: '350',
  length_price: '115'},
  {code: 'MAS',
  product_name: 'Massachusetts Newsline',
  base_price: '350',
  length_price: '115'},
  {code: 'MIA',
  product_name: 'Miami Newsline',
  base_price: '350',
  length_price: '115'},
  {code: 'MIC',
  product_name: 'Michigan Newsline',
  base_price: '350',
  length_price: '115'},
  {code: 'MID',
  product_name: 'Midwest Newsline',
  base_price: '545',
  length_price: '135'},
  {code: 'MIL',
  product_name: 'Milwaukee Newsline',
  base_price: '350',
  length_price: '115'},
  {code: 'MIN',
  product_name: 'Minneapolis/st. Paul Newsline',
  base_price: '350',
  length_price: '115'},
  {code: 'MIS',
  product_name: 'Mississippi Newsline',
  base_price: '350',
  length_price: '115'},
  {code: 'MNS',
  product_name: 'Minnesota Newsline',
  base_price: '350',
  length_price: '115'},
  {code: 'MON',
  product_name: 'Montana Newsline',
  base_price: '350',
  length_price: '115'},
  {code: 'MOU',
  product_name: 'Missouri Newsline',
  base_price: '350',
  length_price: '115'},
  {code: 'MPH',
  product_name: 'Memphis Newsline',
  base_price: '350',
  length_price: '115'},
  {code: 'NCA',
  product_name: 'North California Newsline',
  base_price: '350',
  length_price: '115'},
  {code: 'NEB',
  product_name: 'Nebraska Newsline',
  base_price: '350',
  length_price: '115'},
  {code: 'NEG',
  product_name: 'New England Region',
  base_price: '445',
  length_price: '115'},
  {code: 'NEH',
  product_name: 'New Hampshire Newsline',
  base_price: '350',
  length_price: '115'},
  {code: 'NEO',
  product_name: 'Northeast Ohio Newsline',
  base_price: '350',
  length_price: '115'},
  {code: 'NEV',
  product_name: 'Nevada Newsline',
  base_price: '350',
  length_price: '115'},
  {code: 'NFL',
  product_name: 'North Florida Newsline',
  base_price: '350',
  length_price: '115'},
  {code: 'NJM',
  product_name: 'New Jersey Newsline+ Key Nyc',
  base_price: '445',
  length_price: '115'},
  {code: 'NJP',
  product_name: 'New Jersey Package',
  base_price: '445',
  length_price: '115'},
  {code: 'NJY',
  product_name: 'New Jersey Newsline',
  base_price: '350',
  length_price: '115'},
  {code: 'NMX',
  product_name: 'New Mexico Newsline',
  base_price: '350',
  length_price: '115'},
  {code: 'NOC',
  product_name: 'North Carolina Newsline',
  base_price: '350',
  length_price: '115'},
  {code: 'NOD',
  product_name: 'North Dakota Newsline',
  base_price: '350',
  length_price: '115'},
  {code: 'NOR',
  product_name: 'Northeast Newsline',
  base_price: '545',
  length_price: '135'},
  {code: 'NWO',
  product_name: 'Northwest Ohio Newsline',
  base_price: '305',
  length_price: '95'},
  {code: 'NYC',
  product_name: 'New York Metro Plus California Newsline',
  base_price: '445',
  length_price: '115'},
  {code: 'NYM',
  product_name: 'Ny Metro Newsline',
  base_price: '445',
  length_price: '115'},
  {code: 'NYS',
  product_name: 'Ny State Newsline',
  base_price: '445',
  length_price: '115'},
  {code: 'OHI',
  product_name: 'Ohio Newsline',
  base_price: '350',
  length_price: '115'},
  {code: 'OKA',
  product_name: 'Oklahoma Newsline',
  base_price: '350',
  length_price: '115'},
  {code: 'ORE',
  product_name: 'Oregon Newsline',
  base_price: '350',
  length_price: '115'},
  {code: 'PAC',
  product_name: 'Pacific Northwest Newsline',
  base_price: '445',
  length_price: '115'},
  {code: 'PEN',
  product_name: 'Pennsylvania Newsline',
  base_price: '350',
  length_price: '115'},
  {code: 'PHC',
  product_name: 'Philadelphia Newsline',
  base_price: '350',
  length_price: '115'},
  {code: 'PHN',
  product_name: 'Phoenix Newsline',
  base_price: '350',
  length_price: '115'},
  {code: 'PHR',
  product_name: 'Philadelphia Region Newsline',
  base_price: '350',
  length_price: '115'},
  {code: 'PIT',
  product_name: 'Pittsburgh Newsline',
  base_price: '350',
  length_price: '115'},
  {code: 'POR',
  product_name: 'Portland Newsline',
  base_price: '350',
  length_price: '115'},
  {code: 'RHO',
  product_name: 'Rhode Island Newsline',
  base_price: '350',
  length_price: '115'},
  {code: 'ROC',
  product_name: 'Rocky Mountain Newsline',
  base_price: '445',
  length_price: '115'},
  {code: 'SAC',
  product_name: 'Sacramento Newsline',
  base_price: '350',
  length_price: '115'},
  {code: 'SCA',
  product_name: 'Southern California Newsline',
  base_price: '350',
  length_price: '115'},
  {code: 'SDO',
  product_name: 'San Diego Newsline',
  base_price: '350',
  length_price: '115'},
  {code: 'SEA',
  product_name: 'Seattle / Puget Sound Newsline',
  base_price: '350',
  length_price: '115'},
  {code: 'SFL',
  product_name: 'South Florida Newsline',
  base_price: '350',
  length_price: '115'},
  {code: 'SFO',
  product_name: 'San Francisco / Bay Area Newsline',
  base_price: '350',
  length_price: '115'},
  {code: 'SIL',
  product_name: 'Silicon Valley Newsline',
  base_price: '350',
  length_price: '115'},
  {code: 'SJO',
  product_name: 'San Jose Newsline',
  base_price: '350',
  length_price: '115'},
  {code: 'SO1',
  product_name: 'Us1 Newsline - Social',
  base_price: '0',
  length_price: '205'},
  {code: 'SOC',
  product_name: 'South Carolina Newsline',
  base_price: '350',
  length_price: '115'},
  {code: 'SOD',
  product_name: 'South Dakota Newsline',
  base_price: '350',
  length_price: '115'},
  {code: 'SOU',
  product_name: 'Southeast Newsline',
  base_price: '545',
  length_price: '135'},
  {code: 'SPO',
  product_name: 'Us1 Sports Newsline',
  base_price: '795',
  length_price: '205'},
  {code: 'STL',
  product_name: 'St. Louis Newsline',
  base_price: '350',
  length_price: '115'},
  {code: 'SWC',
  product_name: 'Southwest Newsline',
  base_price: '445',
  length_price: '115'},
  {code: 'TAU',
  product_name: 'Top Automotive Markets',
  base_price: '575',
  length_price: '150'},
  {code: 'TBM',
  product_name: 'Top Health / Biotech Markets',
  base_price: '575',
  length_price: '150'},
  {code: 'TEF',
  product_name: 'Top Entertainment Markets',
  base_price: '575',
  length_price: '150'},
  {code: 'TEM',
  product_name: 'Top Tech Markets',
  base_price: '575',
  length_price: '150'},
  {code: 'TEN',
  product_name: 'Tennessee Newsline',
  base_price: '350',
  length_price: '115'},
  {code: 'TEX',
  product_name: 'Texas Newsline',
  base_price: '350',
  length_price: '115'},
  {code: 'TEY',
  product_name: 'Top Energy Markets',
  base_price: '575',
  length_price: '150'},
  {code: 'TFM',
  product_name: 'Top Financial Services Markets',
  base_price: '575',
  length_price: '150'},
  {code: 'TMM',
  product_name: 'Top Metals Markets',
  base_price: '575',
  length_price: '150'},
  {code: 'TPI',
  product_name: 'Top Public Interest Markets',
  base_price: '575',
  length_price: '150'},
  {code: 'U1A',
  product_name: 'Us1 Automotive Newsline',
  base_price: '795',
  length_price: '205'},
  {code: 'U1B',
  product_name: 'Us1 Newsline - Environment',
  base_price: '795',
  length_price: '205'},
  {code: 'U1C',
  product_name: 'Us1 Newsline - Education',
  base_price: '795',
  length_price: '205'},
  {code: 'U1D',
  product_name: 'Us1 Newsline - Legal',
  base_price: '795',
  length_price: '205'},
  {code: 'U1E',
  product_name: 'Us1 Energy Newsline',
  base_price: '795',
  length_price: '205'},
  {code: 'U1F',
  product_name: 'Us1 Financial Services Newsline',
  base_price: '795',
  length_price: '205'},
  {code: 'U1G',
  product_name: 'Us1 Newsline - Fashion',
  base_price: '795',
  length_price: '205'},
  {code: 'U1H',
  product_name: 'Us1 Health / Biotech Newsline',
  base_price: '795',
  length_price: '205'},
  {code: 'U1J',
  product_name: 'Us1 Newsline - Food/beverage',
  base_price: '795',
  length_price: '205'},
  {code: 'U1K',
  product_name: 'Us1 Newsline - Homeland Security',
  base_price: '795',
  length_price: '205'},
  {code: 'U1L',
  product_name: 'Us1 Newsline - Travel',
  base_price: '795',
  length_price: '205'},
  {code: 'U1M',
  product_name: 'Us1 Metals Newsline',
  base_price: '795',
  length_price: '205'},
  {code: 'U1P',
  product_name: 'Us1 Public Interest Newsline',
  base_price: '795',
  length_price: '205'},
  {code: 'U1Q',
  product_name: 'Us1 Newsline - Consumer',
  base_price: '795',
  length_price: '205'},
  {code: 'U1T',
  product_name: 'Us1 Technology Newsline',
  base_price: '795',
  length_price: '205'},
  {code: 'US1',
  product_name: 'Us1 National Newsline',
  base_price: '795',
  length_price: '205'},
  {code: 'UTA',
  product_name: 'Utah Newsline',
  base_price: '350',
  length_price: '115'},
  {code: 'VER',
  product_name: 'Vermont Newsline',
  base_price: '350',
  length_price: '115'},
  {code: 'VIR',
  product_name: 'Virginia Newsline',
  base_price: '350',
  length_price: '115'},
  {code: 'WAS',
  product_name: 'Washington Newsline',
  base_price: '350',
  length_price: '115'},
  {code: 'WES',
  product_name: 'West / Southwest Newsline',
  base_price: '545',
  length_price: '135'},
  {code: 'WFL',
  product_name: 'West Florida Newsline',
  base_price: '350',
  length_price: '115'},
  {code: 'WIS',
  product_name: 'Wisconsin Newsline',
  base_price: '350',
  length_price: '115'},
  {code: 'WPA',
  product_name: 'Western Pennsylvania',
  base_price: '350',
  length_price: '115'},
  {code: 'WVA',
  product_name: 'West Virginia Newsline',
  base_price: '350',
  length_price: '115'},
  {code: 'WYO',
  product_name: 'Wyoming Newsline',
  base_price: '350',
  length_price: '115'}
 ])

